package ru.cetelem;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2019-01-09T22:12:58.512+03:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "TestService1Service", 
                  wsdlLocation = "classpath:wsdl/helloworld.wsdl",
                  targetNamespace = "http://cetelem.ru/") 
public class TestService1Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cetelem.ru/", "TestService1Service");
    public final static QName TestService1Port = new QName("http://cetelem.ru/", "TestService1Port");
    static {
        URL url = TestService1Service.class.getClassLoader().getResource("wsdl/helloworld.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(TestService1Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/helloworld.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public TestService1Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestService1Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestService1Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public TestService1Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TestService1Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TestService1Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns TestService1
     */
    @WebEndpoint(name = "TestService1Port")
    public TestService1 getTestService1Port() {
        return super.getPort(TestService1Port, TestService1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestService1
     */
    @WebEndpoint(name = "TestService1Port")
    public TestService1 getTestService1Port(WebServiceFeature... features) {
        return super.getPort(TestService1Port, TestService1.class, features);
    }

}
