package ru.cetelem;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2019-01-09T22:12:58.473+03:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://cetelem.ru/", name = "TestService1")
@XmlSeeAlso({ObjectFactory.class})
public interface TestService1 {

    @WebMethod
    @RequestWrapper(localName = "helloWorld1", targetNamespace = "http://cetelem.ru/", className = "ru.cetelem.HelloWorld1")
    @ResponseWrapper(localName = "helloWorld1Response", targetNamespace = "http://cetelem.ru/", className = "ru.cetelem.HelloWorld1Response")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String helloWorld1(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
